start-jsk/rtmros_choreonoid

hrpsys_ros_bridge_jvrc/euslisp/4legs-walking.l
`min-loop`をirteusで設定したので（https://github.com/euslisp/jskeus/pull/273）消しました。
@eisoku9618, @YuOhara
:fullbody-inverse-kinematicsがはやくなります（挙動がかわることはあるかも）
=> Remove min loop according to https://github.com/euslisp/jskeus/pull/273

jvrc_models/JAXON_JVRC/LLEG_LINK5_L.wrl, jvrc_models/JAXON_JVRC/bounding_box/LLEG_LINK5_L.wrl, jvrc_models/JAXON_JVRC/convex_hull/LLEG_LINK5_L.wrl
詳細モデルの左足平，convex_hullモデルの左足の位置がずれている気がします．
=> fix LLEG_LINK5_L translation

hrpsys_ros_bridge_jvrc/euslisp/4legs-walking.l, hrpsys_ros_bridge_jvrc/euslisp/jaxon_jvrc-interface.l, hrpsys_ros_bridge_jvrc/euslisp/jaxon_jvrc-utils.l
- jaxon_jvrcのハンドの接触点を追加するついでにjaxon_jvrc-util.lを追加
- jaxon_jvrcモデルを使うように変更
- 二足歩行でナロースペースを移動するモードの追加
related issue :  https://github.com/start-jsk/rtmros_choreonoid/issues/66
=> Update jaxon red jvrc

hrpsys_ros_bridge_jvrc/euslisp/4legs-walking.l
https://github.com/euslisp/jskeus/pull/274 にて，4脚歩行foot step generatorをupstreamであるjskeusの方へ移したので，そちらの関数を使うように変更しました．
original discussion : https://github.com/start-jsk/rtmros_choreonoid/pull/70
=> [hrpsys_ros_bridge_jvrc/euslisp] use upstream function

hrpsys_ros_bridge_jvrc/launch/vision_connect.launch
https://github.com/start-jsk/rtmros_choreonoid/pull/138
もともとjoint_statesを見ていたコードが、/multisense_local/joint_statesを見るように変更されていたので、
実機に近づける形で、大本のlaunchでrelayするノードを加えました。
本来は multisense_local/joint_statesはmultisenseのjoint_statesだけ出すのが実機と一致するみたいなのですが、こちらでも必要なコードは動きます。
点群が出るところまで確認しました。
=> [visul_connect] add dammy relay for multisense

hrpsys_choreonoid_tutorials/config/JAXON_RED_DRCBOX.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_VALVE.cnoid.in, hrpsys_choreonoid_tutorials/launch/jaxon_red_choreonoid.launch
Use JAXON_RED(Robot)0 instead of JAXON_RED for simulator instance name to keep compatibility with hrpsys-simulator.
=> Use JAXON_RED(Robot)0 instead of JAXON_RED for simulator instance name to keep compatibility with hrpsys-simulator.

hrpsys_choreonoid/launch/startup_choreonoid.launch, hrpsys_choreonoid_tutorials/launch/jaxon_red_choreonoid.launch, hrpsys_choreonoid_tutorials/scripts/jaxon_red_rh_setup.py, hrpsys_choreonoid_tutorials/scripts/jaxon_red_setup.py, hrpsys_choreonoid_tutorials/src/hrpsys_choreonoid_tutorials/choreonoid_hrpsys_config.py
Enable to connect setuplogger for CONSTRAINT_FORCE.
Default = not logging CONSTARINT_FORCE.
```
rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launch 
```
If the following argument is true, log CONSTRAINT_FORCE:
```
rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launch CONNECT_CONSTRAINT_FORCE_LOGGER_PORTS:=true
```
=> Enable to connect setuplogger for CONSTRAINT_FORCE

hrpsys_choreonoid/launch/choreonoid.launch
Use LANG environment on the original terminal to display choreonoid both in English and Japanese.
https://github.com/start-jsk/rtmros_choreonoid/issues/172
=> Use LANG environment on the original terminal to display choreonoid both in English and Japanese.

hrpsys_choreonoid/launch/run_choreonoid.sh
choreonoidのプロセスが残っている場合は、killして抜けるようにしました。
抜けるようにしてあるのは、残っていたchoreonoidが現にあげているlaunchの
他のrtcなどに影響を与えている可能性があるかもしれないと思ったからです。
その場合、落ち着いてもう一度上げ直しましょう
=> kill choreonoid process, if exists

hrpsys_choreonoid/CMakeLists.txt, hrpsys_choreonoid/src/GroundTruthROSBridge.cpp, hrpsys_choreonoid/src/GroundTruthROSBridge.h, hrpsys_choreonoid/src/GroundTruthROSBridgeComp.cpp, hrpsys_choreonoid_tutorials/launch/jaxon_red_vision_connect.launch
=> Add ground truth ros bridge

README.md, hrpsys_choreonoid/scripts/hrpsys_config_sample.py, hrpsys_choreonoid_tutorials/launch/jaxon_red_vision_connect.launch
hrpsys_config.pyをchoreonoidのpythonコンソール内で使うサンプルを追加しました。
https://github.com/fkanehiro/hrpsys-base/pull/1083 hrpsysをこのPR以降にしてください。
また、PRがちょっと不完全でして、デフォルトのネームサーバーを止めてください
~~~
sudo service omniorb4-nameserver stop
~~~
=> Add sample for using hrpsys_config.py

README.md
aptですでにchoreonoid入れちゃっている人が後からソースで入れる際に，
正しくソース版で上書かれるようにPATHの順番変えました．
=> Update README about PKG_CONFIG_PATH ans PATH

hrpsys_choreonoid_tutorials/config/JAXON_RED_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/launch/jaxon_red_choreonoid.launch
実時間で回らない環境(`rostopic hz /joint_states -w 100`のaverage rateが100より大きい)
のために`rtmlaunch hrpsys_choreonoid_tutorials jaxon_red_choreonoid.launch USE_VISION:=False`でVISIONを使わなくなる設定を追加してみました．
デフォルトで`USE_VISION:=true`なので今までの使い方に影響はありません
`USE_VISION:=False`で僕はaverage rate:128→102くらいになりました．
.cnoid中のGLVisionSimulatorアイテムはあってもなくても速度は変わらなかったので新しく.cnoid追加したりはしていません．
=> add USE_VISION argument

hrpsys_choreonoid/CMakeLists.txt, hrpsys_choreonoid/config/CHIDORI.conf, hrpsys_choreonoid/config/CHIDORICustomizer.yaml, hrpsys_choreonoid/package.xml, hrpsys_choreonoid/src/JAXONCustomizer.cpp, hrpsys_choreonoid_tutorials/launch/chidori_choreonoid.launch
`JAXONCustomizer.cpp`の内部で設定していた一部パラメータを，外部のyamlファイルから与えられるように変更しました．
とりあえずchidoriだけですが，
`<robot_name>_choreonoid.launch`
の内部でconfing fileのpathをenvにセットし，
`JAXONCustomizer.cpp`
でenvのpathを取得しconfig fileを読み，センサなどのパラメータを取得するようにしました．
config fileの名前は`<ROBOT_NAME>Customizer.yaml`にしてあります.
=> add yaml file and read it from JAXONCustomizer

hrpsys_choreonoid/launch/run_choreonoid.sh
Ctrl+Cを押した時，run_choreonoid.shに対してSIGTERMやSIGKILLが呼ばれてしまいChoreonoidが落ちない現象が頻発していたので，確実に落ちるようにしました．
子プロセスのみ落とすはずで， #287 のようにChoreonoidを複数立ち上げる場面でも問題はないはずです．
=> [hrpsys_choreonoid/launch/run_choreonoid.sh] Kill choreonoid certainly

hrpsys_choreonoid/CMakeLists.txt
ref: #282 
aptのhrpsysをincludeしようとしてビルドが通らないことが多々あるのでその修正です．
#282 の修正だけではhrpsys src + openrtm apt といった組み合わせの時依然として問題が起こっていたので，そちらの修正をした上でinclude_directoriesやlink_directoriesを整理しました．
=> [CMakeLists.txt] Fix include directories path order

hrpsys_choreonoid_tutorials/config/CHIDORI_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_BLUE_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_TUTORIALS.cnoid.in
最新版のChoreonoidにはfloor.wrlが消されているので.bodyの方を使用するようにしました．
Version 1.6でも問題なく動作します．
=> [hrpsys_choreonoid_tutorials/config] Use floor.body instead of floor.wrl

hrpsys_choreonoid/launch/add_objects.py
これまで，add_objects.pyで読み込むyamlファイルの，各物体の箇所に
```
static: true
```
と書くと，
その物体のルートリンクはworldに固定されるものの，その物体の関節は固定されませんでした．
room73B2のような物体が多いファイルを読み込むと，環境に存在する物体の関節が多いためシミュレーションが遅くなる(0.1倍速くらい)という問題があったため，
新たに
```
static_joint: true
```
と書くと，物体の関節が固定されるようにしました．
この変更によって，環境の全ての物体に
```
static: true
static_joint: true
```
と書くと，room73B2のような環境であっても，自分の環境ではほぼ1倍速でシミュレーションできるようになりました．
=> [hrpsys_choreonoid/add_objects.py] add static_joint option

hrpsys_choreonoid/CMakeLists.txt, hrpsys_choreonoid_tutorials/config/CHIDORI_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_BLUE_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_DOOR.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_DRCBOX.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_LOAD_OBJ.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_LOAD_OBJ_NW.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_LOAD_OBJ.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_TUTORIALS.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_VALVE.cnoid.in
開発版のchoreonoidの変更に対応しました
- cmakeポリシーの変更
- プロジェクトファイルでのロボットモデルの読み込みに関する変更 (https://github.com/s-nakaoka/choreonoid/pull/242#issuecomment-648600032 にある通りformatを追加)
おそらくrelease-1.7で使っている人が殆どだと思いますが，release-1.7でもシミュレーションの起動とgo-posまでは確認しました
=> Support latest choreonoid

.from_source.rosinstall, README.md
README.mdに，hrpsysやopenhrp3をsourceから入れる場合の手順を追加しました．現在のrtmros_choreonoidのwikiに書いてある.rosinstallと同じものです．
@kindsenior
=> add from_source.rosinstall

hrpsys_choreonoid/iob/CMakeLists.txt
https://github.com/start-jsk/rtmros_choreonoid/pull/349 の一部です。
https://github.com/start-jsk/rtmros_choreonoid/issues/339 で報告されている、ソースのhrpsysでもROBOT_IOB_VERSIONが3になるバグを直すPRです。
hrpsysのバーションはaptとsourceで同じになっているので、hrpsys_PREFIXが/opt/rosから始まるかどうかでhrpsysがaptかソースかを判定します。
**With hrpsys APT**
```
rtmros_choreonoid/hrpsys_choreonoid/lib$ nm RobotHardware_choreonoid.so
[中略]
U write_accelerometer_offset
U write_command_angle
U write_command_angles
U write_command_torques
U write_command_velocities
U write_dgain
U write_digital_output
U write_digital_output_with_mask
U write_force_offset
U write_gyro_sensor_offset
U write_pgain
U write_power_command
U write_servo
```
**With hrpsys SOURCE**
```
rtmros_choreonoid/hrpsys_choreonoid/lib$ nm RobotHardware_choreonoid.so
[中略]
U write_accelerometer_offset
U …
```
=> [hrpsys_choreonoid] build with ROBOT_IOB_VERSION=4 if hrpsys is installed from source

.from_source.rosinstall, .travis.rosinstall, .travis.rosinstall.melodic, README.md, hrpsys_choreonoid_tutorials/CMakeLists.txt, hrpsys_choreonoid_tutorials/README.md, hrpsys_choreonoid_tutorials/launch/jaxon_jvrc_choreonoid.launch, hrpsys_choreonoid_tutorials/launch/jaxon_red_choreonoid.launch
https://github.com/start-jsk/rtmros_choreonoid/pull/345
rtmros_chorenoidのREADMEやインストール手順では、privateなモデルを使用しないようにしました。
また、jaxon_jvrc_choreonoid.launchを実行するとjsk_robot_startupとcnoidファイルが無いエラーになったので、jsk_robotを.rosinstallに追加し、jaxon_jvrc_choreonoid.launchのtaskをcnoidファイルが存在するものに変更しました。
=> fix README not use private models

hrpsys_choreonoid/iob/iob.cpp
https://github.com/start-jsk/rtmros_choreonoid/pull/349 の一部です。
実機はservo offの状態から起動しますが、シミュレーションでは時間短縮のためにいきなり立った状態から開始するので、実機では`servo on`時にhrpsysで行われる処理を、シミュレーションではiob内で最初から行う必要があります。
pdgains.file_nameの値を実機に入力する処理は、実機では`servo on`時(厳密にはwrite_pgain等が呼ばれたとき)にhrpsysで行われます。このPRによって、シミュレーションでは開始時にiob内でpdgains.file_nameの値を読むようになります。
関連するissue https://github.com/start-jsk/rtmros_choreonoid/pull/326#issue-405959857
この変更によって、実機とシミュレーションで同じpdgains.file_nameのファイルを使用することが可能になります。`rtmros_choreonoid_tutorials`以下にあるロボットの中で、実機とシミュレーションで異なるpdgains.file_nameのファイルを使っているロボットについて、https://github.com/start-jsk/rtmros_tutorials/pull/597 で修正しました。
=> [hrpsys_choreonoid/iob.cpp] load pdgains.file_name on initialize

hrpsys_choreonoid_tutorials/config/TABLIS_BASE_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/TABLIS_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/launch/tablis_base_choreonoid.launch, hrpsys_choreonoid_tutorials/launch/tablis_choreonoid.launch, hrpsys_choreonoid_tutorials/scripts/tablis_base_rh_setup.py, hrpsys_choreonoid_tutorials/src/hrpsys_choreonoid_tutorials/choreonoid_hrpsys_config.py
https://github.com/start-jsk/rtmros_choreonoid/pull/340 に加えて、
TABLISのシミュレーションを行うために必要だった変更点です。
- TABLIS実機は`JCM_TORQUE`モードで動いているため、`hrpsys_choreonoid`のiobも`JCM_TORQUE`モードに対応させました https://github.com/start-jsk/rtmros_choreonoid/pull/349/commits/6efd6a853e0bb4e989afd68fcc59b859705f4600
- hrpsysをソースから入れても-DROBOT_IOB_VERSION=3でビルドされてしまう問題https://github.com/start-jsk/rtmros_choreonoid/issues/339 を解消しました。https://github.com/start-jsk/rtmros_choreonoid/pull/349/commits/d92e8e6e1b6b682f37168aa2a9351cbc52437b78
- これまでは関節ゲインとして、シミュレーション開始直後は`pdgains_sim_file_name`の値が使われ、`write_pgain`等を一回呼ぶと以降は`pdgains_sim_file_name`の値に`pdgains.file_name`の値を掛けた値が使われていました。シミュレーション開始直後に立てない問題があったので、常に`pdgains_sim_file_name`の値に`pdgains.file_name`の値を掛けた値が使われるようにしました。https://github.com/start-jsk/rtmros_choreonoid/pull/349/co …
=> fix for TABLIS simulation and enable JCM_TORQUE mode

hrpsys_choreonoid_tutorials/config/footsal.yaml.in, hrpsys_choreonoid_tutorials/config/soccer.yaml.in, hrpsys_choreonoid_tutorials/euslisp/action_and_perception/kick-ball-demo.l, hrpsys_choreonoid_tutorials/launch/perception/image_processing.launch, hrpsys_choreonoid_tutorials/launch/perception/tracking_recognition.launch
jaxonのシミュレーションでRobotHardwareを使うバージョンがデフォルトになったことに伴って、標準のロボット方向が違ってしまったため、環境側をロボットの方向に合わせました。
また、画像認識で小さい画面が出るようにしました。
現状のrtmros_choreonoidで、以下のコマンドで
rtmlaunch hrpsys_choreonoid_tutorials jaxon_jvrc_choreonoid.launch
roslaunch hrpsys_choreonoid_tutorials tracking_recognition.launch resized_gui:=true
roseus $(rospack find hrpsys_choreonoid_tutorials)/euslisp/action_and_perception/kick-ball-demo.l '(kick-ball-to-goal-demo)'
以下と同様にロボットシミュレーションができることを確認しました。
https://www.youtube.com/watch?v=tCI5L__FYic
=> Fix footsal

hrpsys_choreonoid_tutorials/scripts/jaxon_blue_rh_setup.py, hrpsys_choreonoid_tutorials/scripts/jaxon_red_rh_setup.py, hrpsys_choreonoid_tutorials/scripts/jaxon_red_setup.py
motor_joint(multisenseのチルトレーザ)関節のjointIdが設定されていないため，
https://github.com/start-jsk/rtmros_choreonoid/blob/be0a77e942bfa9f2fa3391f53cc1a8ef991f8754/hrpsys_choreonoid_tutorials/scripts/jaxon_red_rh_setup.py#L45
を行うとhrpsyが落ちる場合があることの修正です
このPRがなくても
https://github.com/fkanehiro/hrpsys-base/pull/1315
にてhrpsysが落ちること自体は解決されますが，既にmultisenseがSoftErrorLimiterの監視対象から外れているので設定する必要もないため，limitの設定を除外しました
=> [jaxon_red_setup.py][jaxon_red_rh_setup.py] do not set error limit to motor_joint (multisense)
