start-jsk/rtmros_choreonoid

hrpsys_choreonoid/CMakeLists.txt, hrpsys_choreonoid/launch/choreonoid.launch, hrpsys_choreonoid/launch/run_choreonoid.sh, hrpsys_choreonoid/run_choreonoid.sh
update run_choreonoid.sh for parsing rtm options
=> add choreonoid.launch and update run_choreonoid.sh

jvrc_models/scripts/download_models.sh
spreader の.l, .stl .daeを作ってprivateなところに置いたので、それをdownloadするscriptを加えました。
=> add download script for spreader

hrpsys_ros_bridge_jvrc/launch/vision_connect.launch, hrpsys_ros_bridge_jvrc/models/jaxon_jvrc.yaml
https://github.com/start-jsk/rtmros_choreonoid/issues/53
=> fix frame_id of head range

hrpsys_ros_bridge_jvrc/launch/jaxon_jvrc_choreonoid.launch
slam加わりましたが、結構ずれてます。
laserも一通り加わったと思います。
=> add multisense local launch

hrpsys_ros_bridge_jvrc/launch/vision_connect.launch
add needed frame for terrain task
=> add needed frame : head_root

hrpsys_ros_bridge_jvrc/euslisp/4legs-walking.l
=> Update 4leg walk parameter

hrpsys_ros_bridge_jvrc/scripts/jaxon_jvrc_hrpsys_config.py
@YutaKojio 
ST, autobalancer, impedance controllerをスタートするようにしてみました。
スタートできているか確認してください。
=> starting ST,AutoBalancer,ImpedanceC on hrpsys_config.py

hrpsys_ros_bridge_jvrc/scripts/roslaunch.sh
トラップはうまく行っていませんが、スリープは短くなっています。
=> fix roslaunch.sh

hrpsys_ros_bridge_jvrc/launch/jvrc_task_R3A.launch
=> add launch for task R3A (normal estimation and hsi color filter)

hrpsys_ros_bridge_jvrc/euslisp/walking_config.l
Added kick-mode and walking-pose functions to move large obstacle for jvrc task R4
=> Add kick-mode and walking-pose functions

hrpsys_ros_bridge_jvrc/launch/jvrc_task_R3A.launch
add QRcode reader node for reading code inside the car in task R3A
=> add QRcode reader

hrpsys_ros_bridge_jvrc/euslisp/walking_config.l
Modified default-step-time and stride-parameter for kick-mode
=> Modify gait-generator-param for kick-mode

hrpsys_ros_bridge_jvrc/euslisp/cross-step.l
add cross-step walking for task R2AB
=> add cross-step.l

hrpsys_ros_bridge_jvrc/euslisp/jaxon_jvrc-recovery.l
@eisoku9618 さん
push recoveryを追加しました．
```start-push-recovery-loop``` を最初に実行しておけばいいです．
https://drive.google.com/open?id=0B9Cu2eewhmiwLXpsNjd2c0ZYQUk
=> add push-recovery

hrpsys_ros_bridge_jvrc/euslisp/jvrc-debri-motion.l, jvrc_models/models/debris3-visual-default.dae, jvrc_models/models/debris5-visual.dae
add motion to remove debris and decide the stand poit in front of debtis
=> add motion for removing debris

hrpsys_ros_bridge_jvrc/euslisp/walking_config.l
Changed default-step-time and stride-parameter to default value for kick-mode
=> Modify gait generator parameters for kick-mode

hrpsys_ros_bridge_jvrc/launch/R2C.launch
これで rviz からマーカーで移動することができるまでにかかる時間が``*ri*``を作る時間と同じ程度になりました．
=> [hrpsys_ros_bridge_jvrc/euslisp] remove unused nodes for speed up

hrpsys_ros_bridge_jvrc/euslisp/jvrc-debri-motion.l
Added debris5 remove function for jvrc task R4
=> Add debris5 remove function for task R4

hrpsys_ros_bridge_jvrc/CMakeLists.txt, hrpsys_ros_bridge_jvrc/config/JVRC_FLAT.cnoid.in
=> add world of simple flat floor

hrpsys_ros_bridge_jvrc/config/JVRC_VALVE.cnoid.in
=> fix missing config

hrpsys_choreonoid_tutorials/CMakeLists.txt, hrpsys_choreonoid_tutorials/config/JAXON_RED_VALVE.cnoid.in
=> add VALVE task

hrpsys_choreonoid/launch/ros_bridge_choreonoid.launch, hrpsys_choreonoid_tutorials/scripts/jaxon_red_setup.py
enable to use ReferenceForceUpdater in hrpsys_choreonoid_tutorials/jaxon_red_choreonoid.launch
=> [hrpsys_choreonoid/launch/,hrpsys_choreonoid_tutorials/scripts

hrpsys_choreonoid_tutorials/scripts/chidori_rh_setup.py
#198 の修正です(再)．
(2016/08/03現在rtmros_tutorials/hrpsys_ros_bridge_tutorials/CMakeLists.txtのHRP2Wまわりでビルドが通らないようですが，コメントアウトしてビルドして動作することを確認しました)
=> CHIDORI(Robot)0 -> CHIDORI

hrpsys_choreonoid_tutorials/config/flat.yaml.in
https://github.com/start-jsk/rtmros_choreonoid/issues/205
=> add flat.yaml.in

hrpsys_choreonoid/scripts/external_force_sample.py, hrpsys_choreonoid/scripts/forced_position_sample.py
choreonoidのpythonスクリプトのサンプルを追加しました。
=> [hrpsys_choreonoid] add python scripts sample for choreonoid

hrpsys_choreonoid_tutorials/package.xml, hrpsys_ros_bridge_jvrc/package.xml
- roseus_msgs is no logner rquried
- roseus_msgs is no logner rquried
@kyawawa please use rosdep and wstool
=> fix to work with rosdep install

hrpsys_choreonoid_tutorials/launch/jaxon_jvrc_choreonoid.launch
https://github.com/jsk-ros-pkg/jsk_robot/pull/783
=> [JAXON_JVRC] add vision launch

hrpsys_choreonoid/scripts/choreonoid-service-client.l, hrpsys_choreonoid/scripts/ros_service_server.py, hrpsys_choreonoid_tutorials/config/CHIDORI_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_DOOR.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_DRCBOX.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_LOAD_OBJ.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/config/JAXON_RED_RH_LOAD_OBJ.cnoid.in
以下のように、reset-position, add-external-forceをROSから呼べるようにしました。
~~~
(reset-position :robot "CHIDORI" :coords (make-coords :pos #f(0 0 1000) :rpy (list pi/2 0 0)))
~~~
cnoid.inも更新したので、--force-cmakeをつけてtutorialsをcatkin build し直し、これまでと同じようにlaunchを
上げるだけで、上記のサービスが使えるようになっているはずです。
hrpsys_choreonoid/scripts/ros_service_server.py を読んでもらえれば分かりますが、stringを投げて
choreonoidのpython上でevalするだけの構成なので、デフォルトで用意したものだけでなく任意のコマンドが
実行可能になっていると思います。
=> add ros service for calling python scripts inside the choreonoid

hrpsys_choreonoid_tutorials/scripts/chidori_rh_setup.py, hrpsys_choreonoid_tutorials/scripts/jaxon_red_rh_setup.py, hrpsys_choreonoid_tutorials/scripts/jaxon_red_setup.py
=> set reset-pose on initialize

hrpsys_choreonoid/src/JAXONCustomizer.cpp, hrpsys_choreonoid_tutorials/CMakeLists.txt, hrpsys_choreonoid_tutorials/config/BodyRTC_JAXON_BLUE.RH.conf, hrpsys_choreonoid_tutorials/config/JAXON_BLUE_RH_FLAT.cnoid.in, hrpsys_choreonoid_tutorials/launch/jaxon_blue_choreonoid.launch, hrpsys_choreonoid_tutorials/scripts/jaxon_blue_rh_setup.py
add the files for JAXON_BLUE's choreonoid simulations
(launch, cnoid.in, BodyRTC.conf, setup.py)
and add customizer's and cmake's settings
=> [hrpsys_choreonoid_tutorials] add JAXON_BLUE settings

jvrc_models/models/box-stair.wrl, jvrc_models/models/create-box-stair.l
VRML model of stair (and a program to auto-create one with different size), which is composed of boxes
=> VRML model of stair (and a program to auto-create one with different size)

hrpsys_choreonoid/CMakeLists.txt
=> Activate C++ 11 for choreonoid 1.7

README.md
in README.md, added a way to add external force to robot model using euslisp.
=> wrote the way to use add-external-force in euslisp

hrpsys_choreonoid/iob/CMakeLists.txt
https://github.com/start-jsk/rtmros_choreonoid/pull/297 で誤って小文字のnotを使ってしまっていたので、修正しました。
=> [hrpsys_choreonoid/iob/CMakeLists.txt] not->NOT

.travis.yml, Dockerfile.kinetic
revice https://github.com/start-jsk/rtmros_choreonoid/pull/307
=> [travis] build and push image to dockerhub

hrpsys_choreonoid_tutorials/launch/create_environment_sample.launch
fix https://github.com/agent-system/lecture2019/issues/3
=> [hrpsys_choreonoid_tutorials, create_environment] pass USE_ROBOTHARDWARE

jvrc_models/JAXON_JVRC/JAXON_JVRCmain.wrl, jvrc_models/JAXON_JVRC/JAXON_JVRCmain_hrpsys.wrl, jvrc_models/JAXON_JVRC/JAXON_JVRCmain_hrpsys_bush.wrl
Modify JAXON's mass parameters in simulation to current real JAXON_RED ones
=> modify mass params to current real robot ones

README.md, hrpsys_choreonoid_tutorials/README.md
JAXON_JVRCのための注釈をREADME.mdに追加しました
=> add readme for opensource model

jvrc_models/JAXON_JVRC/JAXON_JVRCmain.wrl, jvrc_models/JAXON_JVRC/JAXON_JVRCmain_hrpsys.wrl, jvrc_models/JAXON_JVRC/JAXON_JVRCmain_hrpsys_bush.wrl
JAXONのマスパラについて、jvrc_modelsについて更新されていなかった部分の更新を行いました。
@kindsenior
=> [JAXON_JVRC] fix jaxon mass param

hrpsys_choreonoid/iob/iob.cpp
https://github.com/start-jsk/rtmros_choreonoid/pull/349 の一部です.
`iob.cpp`をJCM_TORQUEモードに対応させました。
JCM_TORQUEモードとJCM_POSITION_TORQUEモード時の挙動は、https://github.com/start-jsk/rtmros_choreonoid/pull/326#issuecomment-736192548 及び https://github.com/jsk-ros-pkg/trans_system/issues/778 に従って、単純にトルクとPD制御を足す方式にしました。
=> [hrpsys_choreonoid/iob.cpp] support JCM_TORQUE
